name: Lint Pull Requests

on:
   pull_request:
      branches:
         - main

jobs:
   lint:
      runs-on: ubuntu-latest

      steps:
         - name: ğŸ“¥ Checkout code
           uses: actions/checkout@v4.1.1

         - name: âš™ï¸ Setup Node.js
           uses: actions/setup-node@v4.0.2
           with:
              node-version: '25'

         - name: ğŸ“¦ Install dependencies
           run: npm ci

         - name: ğŸ“ Run lint
           run: npm run lint

         - name: ğŸ“ Check Typescript
           run: npm run check
